import math
import torch

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


# ---------------------------------------------------------------------------
# 2D Boolean Mask converters (Step 1)
# Bridge between (N, C) bool masks and MoEEG's 1D index masks.
# ---------------------------------------------------------------------------


def mask_2d_to_1d_ctx(mask_ctx):
    """Convert (N,C) or (B,N,C) bool context masks to flat grid indices.

    mask_ctx[i, j] = True means patch i, channel j is visible to context encoder.
    Returns a (mN, mC) tensor where each element is the global flattened index
    n*C + c, matching MoEEG's mask_x format.
    """
    if mask_ctx.ndim == 2:
        N, C = mask_ctx.shape
        flattened = torch.arange(N * C, device=mask_ctx.device).reshape(N, C)
        mN = mask_ctx.any(dim=1).sum().item()
        mC = mask_ctx.sum(dim=1).max().item()
        return flattened[mask_ctx].reshape(mN, mC)

    B, N, C = mask_ctx.shape
    flattened = torch.arange(N * C, device=mask_ctx.device).reshape(1, N, C)
    flattened = flattened.expand(B, -1, -1)
    visible_rows = mask_ctx.any(dim=2).sum(dim=1)
    assert (visible_rows == visible_rows[0]).all()
    mN = int(visible_rows[0].item())
    row_counts = mask_ctx.sum(dim=2)
    selected_counts = row_counts[mask_ctx.any(dim=2)]
    assert (selected_counts == selected_counts[0]).all()
    mC = int(selected_counts[0].item())
    return flattened[mask_ctx].reshape(B, mN, mC)


def mask_2d_to_1d_recon(mask_recon):
    """Convert (N,C) or (B,N,C) bool reconstruction masks to flat indices.

    mask_recon[i, j] = True means patch i, channel j needs reconstruction.
    Returns a (Ny,) tensor of global flattened indices n*C + c,
    matching MoEEG's mask_y format.
    """
    if mask_recon.ndim == 2:
        N, C = mask_recon.shape
        flattened = torch.arange(N * C, device=mask_recon.device).reshape(N, C)
        return flattened[mask_recon]

    B, N, C = mask_recon.shape
    flattened = torch.arange(N * C, device=mask_recon.device).reshape(1, N, C)
    flattened = flattened.expand(B, -1, -1)
    counts = mask_recon.flatten(1).sum(dim=1)
    assert (counts == counts[0]).all()
    return flattened[mask_recon].reshape(B, int(counts[0].item()))


def apply_mask(mask, x, batched=False):
    """
    :param x: tensor of shape [B (batch-size), N (num-patches), C, D (feature-dim)]
    :param mask: tensor [mN, mC] containing indices of patches in [N, C] to keep
    """
    B, N, C, D = x.shape
    if batched:
        assert mask.shape[0] == B
        out_shape = tuple(mask.shape[1:])
        mask_keep = mask.reshape(B, -1, 1).expand(-1, -1, D)
        masked_x = torch.gather(x.reshape(B, N * C, D), dim=1, index=mask_keep)
        return masked_x.contiguous().reshape(B, *out_shape, D)

    if len(mask.shape) == 2:
        mN, mC = mask.shape

        mask_keep = mask.reshape((1, mN * mC, 1)).repeat((B, 1, D))
        masked_x = torch.gather(x.reshape((B, N * C, D)), dim=-2, index=mask_keep)
        masked_x = masked_x.contiguous().view((B, mN, mC, D))
    else:
        mN = mask.shape[0]

        mask_keep = mask.reshape((1, mN, 1)).repeat((B, 1, D))
        masked_x = torch.gather(x.reshape((B, N * C, D)), dim=-2, index=mask_keep)
    return masked_x


def apply_mask_t(mask_t, x):
    """
    :param x: tensor of shape [B (batch-size), N (num-patches), C, D (feature-dim)]
    :param mask: tensor [mN, mC] containing indices of patches in [N, C] to keep
    """
    B, N, D = x.shape
    mN = mask_t.shape[0]

    mask_keep = mask_t.reshape((1, mN, 1)).repeat((B, 1, D))
    masked_x = torch.gather(x, dim=1, index=mask_keep)
    return masked_x


# rotary embedding helper functions
def rotate_half(x):
    # x = rearrange(x, '... (d r) -> ... d r', r = 2)
    x = x.reshape((*x.shape[:-1], x.shape[-1] // 2, 2))
    x1, x2 = x.unbind(dim=-1)
    x = torch.stack((-x2, x1), dim=-1)
    # return rearrange(x, '... d r -> ... (d r)')
    return x.flatten(-2)


def apply_rotary_emb(freqs, t, start_index=0, scale=1.):
    """
    Apply rotary positional embeddings to a tensor.

    The rotary embedding rotates each dimension of the input tensor `t`
    based on the corresponding frequency in `freqs`, using cosine and sine functions.
    This rotation helps the model preserve positional information.

    Parameters:
    - freqs (Tensor): The frequency embeddings (sine and cosine values precomputed).
    - t (Tensor): The input tensor to which the rotary embeddings are applied.
    - start_index (int): Start index where the rotation will begin within the tensor `t`.
    - scale (float): Scaling factor for the rotation applied.

    Returns:
    - Tensor: The tensor `t` after rotary positional embeddings have been applied.
    """

    freqs = freqs.to(t.device)

    rot_dim = freqs.shape[-1]

    end_index = start_index + rot_dim

    assert rot_dim <= t.shape[
        -1], f'feature dimension {t.shape[-1]} is not of sufficient size to rotate in all the positions {rot_dim}'

    t_left, t_middle, t_right = t[..., :start_index], t[..., start_index:end_index], t[..., end_index:]

    # Apply rotary embeddings to the middle segment.
    t_rotated_middle = (t_middle * freqs.cos() * scale) + (rotate_half(t_middle) * freqs.sin() * scale)

    return torch.cat((t_left, t_rotated_middle, t_right), dim=-1)

class AverageMeter(object):
    """computes and stores the average and current value"""

    def __init__(self):
        self.reset()

    def reset(self):
        self.val = 0
        self.avg = 0
        self.max = float('-inf')
        self.min = float('inf')
        self.sum = 0
        self.count = 0

    def update(self, val, n=1):
        self.val = val
        try:
            self.max = max(val, self.max)
            self.min = min(val, self.min)
        except Exception:
            pass
        self.sum += val * n
        self.count += n
        self.avg = self.sum / self.count

def grad_logger(named_params):
    stats = AverageMeter()
    stats.first_layer = None
    stats.last_layer = None
    for n, p in named_params:
        if (p.grad is not None) and not (n.endswith('.bias') or len(p.shape) == 1):
            grad_norm = float(torch.norm(p.grad.data))
            stats.update(grad_norm)
            if 'qkv' in n:
                stats.last_layer = grad_norm
                if stats.first_layer is None:
                    stats.first_layer = grad_norm
    if stats.first_layer is None or stats.last_layer is None:
        stats.first_layer = stats.last_layer = 0.
    return stats

class CosineWDSchedule(object):

    def __init__(
        self,
        optimizer,
        ref_wd,
        T_max,
        final_wd=0.
    ):
        self.optimizer = optimizer
        self.ref_wd = ref_wd
        self.final_wd = final_wd
        self.T_max = T_max
        self._step = 0.

    def step(self):
        self._step += 1
        progress = self._step / self.T_max
        new_wd = self.final_wd + (self.ref_wd - self.final_wd) * 0.5 * (1. + math.cos(math.pi * progress))

        if self.final_wd <= self.ref_wd:
            new_wd = max(self.final_wd, new_wd)
        else:
            new_wd = min(self.final_wd, new_wd)

        for group in self.optimizer.param_groups:
            if ('WD_exclude' not in group) or not group['WD_exclude']:
                group['weight_decay'] = new_wd
        return new_wd
